### ISSUE TITLE
I was using it normally and then this happen

### ISSUE THREAD

**Issue by MyNameIsMinhReal** [mehboss/TranspositionRitual#2]
### What happened?

I was try to reactivate the rituals then it not showing up the particals. And when I check the console it said like like in the logs output.

### What was supposed to happen?

I think it should showed all the particals with the color I choose but nothing happen.

### How do I reproduce this issue?

```bash
1. I installed it in my minecraft server and it works perfectly
2. Then I close my server so I could eat some lunch etc.
3. I came back and started the server then try the rituals again but it didn't work.
```

### Relevant log output

```shell
[TPRituals] Task #24236 for TPRituals v1.2 generated an exception

java.lang.IllegalArgumentException: color

at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]

at org.bukkit.Particle$DustOptions.<init>(Particle.java:175) ~[spigot-api-1.20.1-R0.1-SNAPSHOT.jar:?]

at me.mehboss.ritual.LocationManager.noNetwork(LocationManager.java:49) ~[?:?]

at me.mehboss.ritual.LocationManager.spawnLocationParticles(LocationManager.java:121) ~[?:?]

at me.mehboss.ritual.LocationManager.startLocationParticles(LocationManager.java:153) ~[?:?]

at me.mehboss.ritual.RitualManager$2.run(RitualManager.java:331) ~[?:?]

at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:82) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3854-Spigot-3bce793-46c7fc3]

at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:415) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3854-Spigot-3bce793-46c7fc3]

at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1257) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3854-Spigot-3bce793-46c7fc3]

at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:388) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3854-Spigot-3bce793-46c7fc3]

at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1198) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3854-Spigot-3bce793-46c7fc3]

at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1015) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3854-Spigot-3bce793-46c7fc3]

at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.1-R0.1-SNAPSHOT.jar:3854-Spigot-3bce793-46c7fc3]

at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

### Server Version

3854-Spigot-3bce793-46c7fc3

### Plugin Version

v1.2

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of TP Rituals and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello,
Could you pastebin the config with the ritual locations in it? And what color did you attempt to use before encountering this issue?

**Comment by MyNameIsMinhReal** [comment]
# DO NOT TOUCH UNLESS YOU KNOW WHAT YOU ARE DOING #
# INTERNALLY MANAGED BY PLUGIN #

Rituals:
  '[2]':
    Location:
      ==: org.bukkit.Location
      world: world
      x: 182.0
      y: 135.0
      z: 483.0
      pitch: 0.0
      yaw: 0.0
    Owner: 8329ea14-44bb-394d-9916-a24798c549d8
The others one i accidentally deleted it because i think it was fixed the problem but it not work. I was using cyan color before encountered this.

**Comment by mehboss** [comment]
Hello, I will attempt to reproduce it. If I can not reproduce, I can give you a solution. One second.

**Comment by mehboss** [comment]
Hello again, I have released an update which can be found [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-teleportation-rituals-1-8-x-1-20-x-creation-limit-networking-system-%E2%97%84%E2%97%84.110584/update?update=512655). This includes some extra measures against any errors you may encounter. In addition, if you could please replace what is inside of your ritual.yml with this, it should resolve the issue.
https://pastebin.com/nZnB9W2P

If you encounter any additional errors please open another ticket.

Thank you,
Mehboss

**Comment by MyNameIsMinhReal** [comment]
tysm
