### ISSUE TITLE
Doesn't work in 1.16 version

### ISSUE THREAD

**Issue by Krissssik** [mehboss/TranspositionRitual#7]
### What happened?

i'm tryin to install this plugin for my server in 1.16, but its does not start although the site says that it supports lower versions.

### What was supposed to happen?

To start this awesom plugin in 1.16

### How do I reproduce this issue?

```bash
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.18
	at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:361) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:149) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:414) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:322) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:393) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:269) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

### Server Version

1.16.5

### Plugin Version

1.4

### Server Mode

Offline Mode

### Issue Confirmation

- [X] I have downloaded and tried the latest version of TP Rituals and the issue still persists.
- [X] I have provided sufficient information for the issue to be replicated.

**Comment by mehboss** [comment]
Hello, thank you for your patience while I was MIA. Please download the newest update [here](https://www.spigotmc.org/resources/%E2%96%BA%E2%96%BA-teleportation-rituals-1-8-x-1-20-x-creation-limit-networking-system-%E2%97%84%E2%97%84.110584/update?update=564059), and your issue will be resolved.
